# Generates Assets/Resources/Localization/Strings_qps.asset — the pseudo-locale.
#
# Deliberately incomplete: three keys are left out so the English fallback is a path
# something actually walks, rather than a branch only a test double has ever entered.
import io, os, re, uuid

SRC = 'Assets/Resources/Localization/Strings_en.asset'
DST = 'Assets/Resources/Localization/Strings_qps.asset'

# Accented stand-ins, one per ASCII letter. Same letter shapes, so a reviewer can still
# read the screen, but every one exercises a non-ASCII code path.
MAP = {
    'a': 'à', 'b': 'ƀ', 'c': 'ç', 'd': 'đ', 'e': 'é', 'f': 'ƒ',
    'g': 'ğ', 'h': 'ĥ', 'i': 'î', 'j': 'ĵ', 'k': 'ķ', 'l': 'ļ',
    'm': 'ḿ', 'n': 'ñ', 'o': 'ö', 'p': 'þ', 'q': 'ǫ', 'r': 'ŗ',
    's': 'š', 't': 'ţ', 'u': 'ü', 'v': 'ṽ', 'w': 'ŵ', 'x': 'ẋ',
    'y': 'ý', 'z': 'ž',
    'A': 'À', 'B': 'Ɓ', 'C': 'Ç', 'D': 'Đ', 'E': 'É', 'F': 'Ƒ',
    'G': 'Ğ', 'H': 'Ĥ', 'I': 'Î', 'J': 'Ĵ', 'K': 'Ķ', 'L': 'Ļ',
    'M': 'Ḿ', 'N': 'Ñ', 'O': 'Ö', 'P': 'Þ', 'Q': 'Ǫ', 'R': 'Ŗ',
    'S': 'Š', 'T': 'Ţ', 'U': 'Ü', 'V': 'Ṽ', 'W': 'Ŵ', 'X': 'Ẋ',
    'Y': 'Ý', 'Z': 'Ž',
}

# Left untranslated on purpose, so Strings.Get has to fall through to English.
OMITTED = {'hud.combo', 'menu.resolution', 'device.controller_found'}

PLACEHOLDER = re.compile(r'\{\d+\}')


def pseudo(text):
    """Accent every letter and pad by ~35%, leaving {0}-style placeholders untouched.

    The padding is the point as much as the accents: German and Hindi run longer than
    English, and a label that only ever held English fits everything."""
    out = []
    last = 0
    for match in PLACEHOLDER.finditer(text):
        out.append(''.join(MAP.get(ch, ch) for ch in text[last:match.start()]))
        out.append(match.group(0))
        last = match.end()
    out.append(''.join(MAP.get(ch, ch) for ch in text[last:]))
    body = ''.join(out)

    letters = sum(1 for ch in text if ch.isalpha())
    padding = '·' * max(2, int(letters * 0.35))
    return '[' + body + ' ' + padding + ']'


def quote(value):
    """YAML-quote the way Unity does: single quotes, doubled inside."""
    needs = (value != value.strip() or value == ''
             or value[0] in '\'"[]{}&*#?|-<>=!%@`'
             or ': ' in value or ' #' in value)
    return "'" + value.replace("'", "''") + "'" if needs else value


source = io.open(SRC, encoding='utf-8').read()
header, _, body = source.partition('  entries:\n')

entries = re.findall(
    r'  - Key: (.*?)\n    Value: (.*?)\n    Note: (.*?)\n(?=  - Key:|\Z)',
    body, re.S)

assert entries, 'no entries parsed from the English table'


def unquote(raw):
    raw = raw.strip()
    if raw.startswith("'") and raw.endswith("'") and len(raw) >= 2:
        return raw[1:-1].replace("''", "'")
    return raw


lines = []
kept = 0
for key, value, note in entries:
    key = key.strip()
    if key in OMITTED:
        continue
    kept += 1
    lines.append('  - Key: ' + key)
    lines.append('    Value: ' + quote(pseudo(unquote(value))))
    lines.append('    Note: ' + quote('Generated by Tools/make-pseudo-locale.py. Do not translate.'))

header = (header
          .replace('  m_Name: Strings_en', '  m_Name: Strings_qps')
          .replace('  languageCode: en', '  languageCode: qps')
          .replace('  languageName: English', '  languageName: Pseudo (qps)'))

io.open(DST, 'w', encoding='utf-8', newline='\n').write(
    header + '  entries:\n' + '\n'.join(lines) + '\n')

if not os.path.exists(DST + '.meta'):
    io.open(DST + '.meta', 'w', encoding='utf-8', newline='\n').write(
        'fileFormatVersion: 2\n'
        'guid: ' + uuid.uuid4().hex + '\n'
        'NativeFormatImporter:\n'
        '  externalObjects: {}\n'
        '  mainObjectFileID: 11400000\n'
        '  userData: \n'
        '  assetBundleName: \n'
        '  assetBundleVariant: \n')

print('wrote %s: %d of %d keys (%d omitted on purpose)'
      % (DST, kept, len(entries), len(entries) - kept))
